support SendPrivateForwardMessage
wdvxdr1123/ZeroBot pull request #64
Opened 2022-06-18 12:07 UTC by Jiang-Red

2022-06-18 15:40 UTC, fumiama requested changes

2022-06-18 15:40 UTC, fumiama commented on context.go
> +func (ctx *Ctx) SendForward(msg interface{}) message.MessageID {
建议与Send合并，至于判断方法，详见
https://github.com/wdvxdr1123/ZeroBot/blob/2bffe8fb77cd8bcbbc722e4790f8833be5dea2f3/message/message.go#L126-L128

2022-06-18 15:40 UTC, fumiama commented on context.go
> +func (ctx *Ctx) SendChainForward(msg ...message.MessageSegment) message.MessageID {
同样理由，这个就没必要了。

2022-06-18 16:23 UTC, Jiang-Red commented on context.go
> +func (ctx *Ctx) SendForward(msg interface{}) message.MessageID {
改好了，这样改是对的吗（

2022-06-19 04:57 UTC, Jiang-Red commented
测试完发现是有问题的，晚上回来再改改

2022-06-19 16:18 UTC, Jiang-Red commented
https://github.com/wdvxdr1123/ZeroBot/pull/64/commits/b97fe4ddd507198a0e0e5fcb53f5e683512d5720

2022-06-22 07:12 UTC, fumiama approved these changes

2022-06-22 07:15 UTC, fumiama commented
你试试我的修改是否可行

2022-06-22 16:08 UTC, merged