消息模板匹配器
wdvxdr1123/ZeroBot pull request #91
Opened 2024-10-09 02:16 UTC by RikaCelery

旨在提供一种更好的消息匹配方式
避免因可能的onebot扩展导致正则匹配失效

2024-10-09 02:20 UTC, RikaCelery commented on engine.go
> +func OnPattern(rules ...PatternSegment) *Matcher { return On("message", PatternRule(rules...)) }
感觉和其他函数签名有点不太一致

2024-10-09 15:02 UTC, fumiama commented on engine.go
> +func OnPattern(rules ...PatternSegment) *Matcher { return On("message", PatternRule(rules...)) }
可以直接将PatternSegment包装为一个函数，返回闭包`Rule`，如此一来无需新增`OnPattern`即可将其与其它规则结合。

2024-10-09 15:11 UTC, RikaCelery commented on engine.go
> +func OnPattern(rules ...PatternSegment) *Matcher { return On("message", PatternRule(rules...)) }
每一个`Rule`匹配一个消息对象吗🤔

2024-10-09 15:18 UTC, fumiama commented on engine.go
> +func OnPattern(rules ...PatternSegment) *Matcher { return On("message", PatternRule(rules...)) }
不管匹配什么，最后只需要返回true/false。变长参数也未尝不可。

2024-10-10 00:51 UTC, RikaCelery commented on engine.go
> +func OnPattern(rules ...PatternSegment) *Matcher { return On("message", PatternRule(rules...)) }
> 可以直接将PatternSegment包装为一个函数，返回闭包`Rule`，如此一来无需新增`OnPattern`即可将其与其它规则结合。

那感觉有PatternRule就够了，我把这个删掉吧

2024-10-10 03:01 UTC, RikaCelery commented on rules.go
> +			if _, ok := ctx.State[KEY_PATTERN]; !ok {
reply后面有可能会跟一个At消息

2024-10-11 08:10 UTC, fumiama requested changes

2024-10-11 08:10 UTC, fumiama commented on rules.go
> +	Matcher  func(ctx *Ctx, msg message.MessageSegment) bool
没必要，ctx自带msg。

2024-10-11 08:10 UTC, fumiama commented on rules.go
> +type PatternSegment struct {
可新建一个文件`pattern.go`，并写相应的`pattern_test.go`，参见同目录下`shell.go`和`shell_test.go`。

2024-10-11 08:10 UTC, fumiama commented on rules.go
> +	HasValue bool
没必要声明这么多，就一个
```go
type PatternParsed struct {
    Valid bool
    Value any
}
```
另外`type xxx = struct`跟谁学的，不是标准写法。

而且，实际上，就连这struct都不需要，直接返回内部的type，是0值自然就为空。

2024-10-11 08:10 UTC, fumiama commented on rules.go
> +func (p PatternMatched) AsText() PatternTextMatched {
不是As，是Get，直接返回string，无值直接返回0值。其它同。

2024-10-11 08:10 UTC, fumiama commented on rules.go
> +func PatternText(regex string) *PatternSegment {
做成链式比较好。
```go
zero.NewPattern(放一些设置).Text(xxx).At()....
```

2024-10-11 16:10 UTC, RikaCelery commented on rules.go
> +	HasValue bool
我想在返回Parsed结果的时候带上对应的msg，以及解析得到的一些结果，结构打算这样
```go
type PatternParsed struct {
	Valid bool     // optional的时候
	Value any
	Msg   *message.MessageSegment
}
```

2024-10-12 02:24 UTC, RikaCelery commented on rules.go
> +	return func(ctx *Ctx) bool {
TODO: file message 的 Message是空的

2024-10-12 02:28 UTC, RikaCelery commented on rules.go
> +		msgs := make([]message.MessageSegment, 0, len(ctx.Event.Message))
TODO file message

File的Message是空的

2024-10-12 02:58 UTC, RikaCelery commented on rules.go
> +		msgs := make([]message.MessageSegment, 0, len(ctx.Event.Message))
要针对file_upload新建一个FileMessage吗
不确定其他客户端的表现, lagrange的message是空的（或许这个问题应该给lgr提issue？）

2024-10-12 14:51 UTC, fumiama requested changes
还需修复lint。

2024-10-12 14:51 UTC, fumiama commented on pattern.go
> +	pattern := make(Pattern, 0)
```suggestion
	pattern := make(Pattern, 0, 4)
```

2024-10-12 14:51 UTC, fumiama commented on pattern.go
> +		return make([]string, 0)
```suggestion
		return nil
```

2024-10-12 14:51 UTC, fumiama commented on rules.go
> +		msgs := make([]message.MessageSegment, 0, len(ctx.Event.Message))
不必，这个不常用，而且用户可以自己编写扩展的匹配。

2024-10-12 15:17 UTC, fumiama commented
> 还需修复lint。

拉取最新后即可见。

2024-10-12 17:44 UTC, fumiama requested changes

2024-10-12 17:44 UTC, fumiama commented on rules.go
> +// PatternRule check if the message can be matched by the pattern
这个也放pattern.go，放最上面。

2024-10-13 00:13 UTC, RikaCelery commented on rules.go
> +// PatternRule check if the message can be matched by the pattern
我把 `KeyPattern` 也挪过去？

2024-10-13 06:50 UTC, fumiama requested changes

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func (p PatternParsed) GetText() []string {
```suggestion
func (p PatternParsed) Text() []string {
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func (p PatternParsed) GetAt() string {
```suggestion
func (p PatternParsed) At() string {
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func (p PatternParsed) GetImage() string {
```suggestion
func (p PatternParsed) Image() string {
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func (p PatternParsed) GetReply() string {
```suggestion
func (p PatternParsed) Reply() string {
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +		Parse: func(msg *message.Segment) *PatternParsed {
可将`Parse`单独定义在外面方便复用并避免嵌套太深（以下皆同），并将`PatternSegment`设为通过
```go
func NewPatternSegment(typ string, optional bool, parse ...)
```
生成。与此同时，将`PatternSegment`的所有字段改为私有以避免意外更改。

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func PatternRule(pattern *Pattern) Rule {
不必，贯彻链式书写，只需给`*Pattern`加一个函数`AsRule() Rule`即可。

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func (p *Pattern) At(id ...string) *Pattern {
id可以用`message.ID`

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +func containsOptional(pattern Pattern) bool {
既然唯一的使用位置是取其非值，那直接将此函数变为`mustMatchAllPatterns`比较好。

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +		ctx.State[KeyPattern] = make([]*PatternParsed, 0, 1)
1跟0差不多，至少4才有收益。
```suggestion
		ctx.State[KeyPattern] = make([]*PatternParsed, 0, 4)
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +				ctx.State[KeyPattern] = append(ctx.State[KeyPattern].([]*PatternParsed), parsed)
不要每次append都从`ctx.State[KeyPattern]`读写，先放本地变量，最后一次写入。

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +		}
太啰嗦了，最后大部分都归结为`msgs = append(msgs, ctx.Event.Message[i])`，既然如此全部反过来判断更简洁。但我说实话这个判断真没必要，你这实际上是删除了@本人，不删除又何妨，删除了反而会让用户体验不一致。
```suggestion
		for i := 1; i < len(ctx.Event.Message); i++ {
			if ctx.Event.Message[i-1].Type == "reply" && ctx.Event.Message[i].Type == "at" {
				// [reply][at]
				reply := ctx.GetMessage(ctx.Event.Message[i-1].Data["id"])
				if reply.MessageID.ID() != 0 && reply.Sender != nil && reply.Sender.ID != 0 &&  strconv.FormatInt(reply.Sender.ID, 10) == ctx.Event.Message[i].Data["qq"] {
					continue
				}
			}
			msgs = append(msgs, ctx.Event.Message[i])
		}
```

2024-10-13 06:50 UTC, fumiama commented on pattern.go
> +	Valid bool
既然加了Msg字段，直接判断Msg是否nil即可充当Valid的作用。这个字段可以删了。

2024-10-13 06:50 UTC, fumiama commented on rules.go
> +const (
挪全啊😂，我说一块你挪一块是吧。

2024-10-13 07:25 UTC, RikaCelery commented on rules.go
> +const (
((

2024-10-13 07:28 UTC, RikaCelery commented on pattern.go
> +		}
因为回复的时候那个@旧版客户端会自动加上，这个东西会干扰接下来的解析

2024-10-13 07:31 UTC, fumiama commented on pattern.go
> +		}
可以给出示例，如果这个没什么大用的话，直接在preprocess中删去。

2024-10-13 09:41 UTC, RikaCelery commented on pattern.go
> +		}
🤔这么一说我好像确实没见过有功能依赖这个
不过preprocess中每次都getMessage会不会太频繁了

2024-10-13 09:42 UTC, RikaCelery commented on pattern.go
> +	Valid bool
感觉用value来判断更符合语义，不然下面这个判断看起来就有点迷惑了
```go
func (p PatternParsed) Text() []string {
	if p.msg == nil {
		return nil
	}
	return p.value.([]string)
}
```

2024-10-13 09:52 UTC, RikaCelery commented on pattern.go
> +func (p *Pattern) At(id ...string) *Pattern {
这个好像没有公开的构建函数？

2024-10-13 09:59 UTC, RikaCelery commented on pattern.go
> +		Parse: func(msg *message.Segment) *PatternParsed {
所有字段改为私有之后optional要怎么设置呢，加个参数吗

2024-10-13 11:24 UTC, fumiama commented on pattern.go
> +		Parse: func(msg *message.Segment) *PatternParsed {
不是有SetOptional吗

2024-10-13 11:25 UTC, fumiama commented on pattern.go
> +func (p *Pattern) At(id ...string) *Pattern {
message.NewMessageIDFromString / message.NewMessageIDFromInteger

2024-10-13 11:29 UTC, fumiama commented on pattern.go
> +		}
反正回复约等于@其他人，用户可以在Reply后面加一个Optional的At消除可能的匹配。如果真的匹配到了就让用户自己判断。

2024-10-13 11:30 UTC, fumiama commented on pattern.go
> +	Valid bool
你只要保证msg永远在value有值时有值，这样判断就没问题。换句话说，如果msg和valid永远同时有/无值，那么valid必然多余。

2024-10-13 13:02 UTC, RikaCelery commented on pattern.go
> +func (p *Pattern) At(id ...string) *Pattern {
got it

2024-10-13 14:35 UTC, RikaCelery commented on pattern.go
> +		}
> Reply后面加一个Optional的At消除可能的匹配

这样会不会有点麻烦，给Reply加个option默认过滤掉或者不过滤掉？

2024-10-13 14:35 UTC, RikaCelery commented
要不要加个Any匹配任意消息

2024-10-13 14:43 UTC, RikaCelery commented on pattern.go
> +		Parse: func(msg *message.Segment) *PatternParsed {
哦草，斯密马赛
我是go低手

2024-10-13 15:45 UTC, fumiama commented on pattern.go
> +		}
也可以

2024-10-13 15:46 UTC, fumiama commented on pattern.go
> +	Valid bool
msg现在是private，可以加一个`Raw()`返回其值。

2024-10-13 15:46 UTC, fumiama commented
> 要不要加个Any匹配任意消息

也行

2024-10-13 15:48 UTC, fumiama commented
其实有一个和你这个实现的比较类似的东西`extension/filter`，可以参考一下。

2024-10-13 17:12 UTC, RikaCelery commented
> 其实有一个和你这个实现的比较类似的东西`extension/filter`，可以参考一下。

写的真好看🥳

2024-10-13 17:13 UTC, fumiama requested changes

2024-10-13 17:13 UTC, fumiama commented on pattern.go
> +		"text", false, func(msg *message.Segment) *PatternParsed {
把这个parse的func提出来，我是这个意思。

2024-10-13 17:19 UTC, RikaCelery commented on pattern.go
> +		"text", false, func(msg *message.Segment) *PatternParsed {
这样吗
```go

// Text use regex to search a 'text' segment
func (p *Pattern) Text(regex string) *Pattern {
	pattern := NewPatternSegment(
		"text", false, parseText(regex),
	)
	*p = append(*p, *pattern)
	return p
}

func parseText(regex string) func(msg *message.Segment) *PatternParsed {
	re := regexp.MustCompile(regex)
	return func(msg *message.Segment) *PatternParsed {
		s := msg.Data["text"]
		s = strings.Trim(s, " \n\r\t")
		matchString := re.MatchString(s)
		if matchString {
			return &PatternParsed{
				value: re.FindStringSubmatch(s),
				msg:   msg,
			}
		}

		return &PatternParsed{
			value: nil,
			msg:   nil,
		}
	}
}
```

2024-10-13 17:34 UTC, fumiama commented on pattern.go
> +		"text", false, func(msg *message.Segment) *PatternParsed {
主要是为了让用户可见。
```go
func NewTextParser(regex string) ...
```
同时声明
```go
type Parser func(msg *message.Segment) *PatternParsed
```
用户想添加自定义Parser
```go
pattern.Add("text", false, ...)
```
而不需要`NewPatternSegment`

2024-10-14 00:33 UTC, RikaCelery commented on pattern.go
> +		"text", false, func(msg *message.Segment) *PatternParsed {
原来如此，已修改

2024-10-14 05:20 UTC, fumiama requested changes

2024-10-14 05:20 UTC, fumiama commented on pattern.go
> +			if segment.cleanRedundantAt {
就是说这是一个全局的配置，所以
```go
type Pattern []PatternSegment
```
可以改为
```go
type Pattern struct {
    cleanRedundantAt bool
    segments []PatternSegment
}
```
并在NewPattern时传入。

2024-10-14 05:20 UTC, fumiama commented on pattern.go
> +	parse            func(msg *message.Segment) *PatternParsed
既然已经声明了Parser这个类型，**所有**func声明都可以替换以避免杂乱。

2024-10-14 05:20 UTC, fumiama commented on pattern.go
> +		for i := 1; i < len(ctx.Event.Message); i++ {
不要在循环中判断should clean。事实上如果不清理，根本没必要新建msgs并拷贝，直接return即可。

2024-10-14 05:20 UTC, fumiama commented on pattern.go
> +	patternState := make([]*PatternParsed, 0, 4)
这个长度应该是可以确定的吧，就是len(pattern)，直接make这么长然后用i索引赋值就行。另外，类型可用[]PatternParsed，这样一来如果无匹配就直接continue，默认值零就是
```go
PatternParsed {
	value: nil,
	msg:   nil,
}
```

2024-10-14 05:20 UTC, fumiama commented on pattern.go
> +			parsed = &PatternParsed{
这里就不用了

2024-10-14 14:13 UTC, RikaCelery commented on pattern.go
> +			if segment.cleanRedundantAt {
已修改

2024-10-14 15:03 UTC, fumiama approved these changes

2024-10-14 15:03 UTC, merged