AtPattern识别@+qq号
wdvxdr1123/ZeroBot pull request #94
Opened 2024-11-07 08:27 UTC by RikaCelery

2024-11-07 08:53 UTC, RikaCelery commented on pattern.go
> +							if member.Get("card").Str == ats[i][1] || member.Get("nickname").Str == ats[i][1] {
太深了太深了！（x

2024-11-07 09:15 UTC, RikaCelery commented on pattern.go
> +							if member.Get("card").Str == ats[i][1] || member.Get("nickname").Str == ats[i][1] {
短了，喜（X

2024-11-09 05:40 UTC, fumiama requested changes

2024-11-09 05:40 UTC, fumiama commented on pattern.go
> +func NewPattern(cleanRedundantAt ...PatternOption) *Pattern {
传*PatternOption即可，根据nil与否判断是否采用默认值。尽量不要使用这种...代替可选参数的方式，可能会让用户困惑。

2024-11-09 05:40 UTC, fumiama commented on pattern.go
> +	cleanRedundantAt bool
这是呈现给用户自定义的struct，内部必须为public。

2024-11-09 05:40 UTC, fumiama commented on pattern.go
> +func extractStringAt(ctx *Ctx, msg string) []message.Segment {
ctx自带msg，直接传index并将其作为ctx之成员函数，形如
```go
func (ctx *Ctx) splitAtInText(index int) []message.Segment
```

2024-11-09 06:18 UTC, RikaCelery commented on pattern.go
> +func NewPattern(cleanRedundantAt ...PatternOption) *Pattern {
那所有的NewPattern就必须传入一个nil了，会不会太麻烦了

2024-11-09 06:20 UTC, fumiama commented on pattern.go
> +func NewPattern(cleanRedundantAt ...PatternOption) *Pattern {
提醒用户这里有个参数，再说nil就三个字母😂

2024-11-09 06:40 UTC, merged